### ISSUE TITLE
PicoScope2000Open.vi Unable to open PicoScope

### ISSUE THREAD

**Issue by MrWang2334** [picotech/picosdk-ni-labview-examples#3]
### Setup

* Example filename:ps2000\32(64)-bit-examples\PicoScope2000Open.vi 
* Version of LabVIEW (32/64-bit & Service Pack):LabVIEW2017-32bit/64bit
* Pico Technology device model:PicoScope2206B
* Driver name and version number:PicoSDK_32_10.6.12.41.exe/PicoSDK_64_10.6.12.41.exe
* Operating system:Windows 10 Family Chinese Edition 64bit
* USB port type	(e.g. 2.0):3.0

### Description
The PicoScope 2206 can be used normally by PicoScope 6, but cannot be used with labview ps2000.dll.
On the same computer。

#### Steps to reproduce the issue
Run the PicoScope2000Open.vi

Use one of two methods to describe the issue:

1. A list of steps to reproduce the issue. 
1. A natural language description of what you were doing when the issue occurred if you are unable to work out what the steps are. 

#### Actual Result
PicoScope2000Open.vi handle renturn 0,ubalbe to open picoscope

#### Expected Result
PS.dll shoule can open picoscope

### Notes

Include any other information here.

![clipboard](https://user-images.githubusercontent.com/41093068/43299560-3d5bcf20-918d-11e8-9810-765ba595c6e3.png)
![clipboard1](https://user-images.githubusercontent.com/41093068/43299599-5c1acf88-918d-11e8-86ab-a9761ab63677.png)

**Comment by hsmistry** [comment]
@MrWang2334 , the PicoScope 2206B uses the API functions from the ps2000a driver. Please use the examples from the ps2000a folder in this repository.

**Comment by MrWang2334** [comment]
Thanks fo your reply,It‘s work fine.
