### ISSUE TITLE
PicoScope 2206B with Labview 

### ISSUE THREAD

**Issue by Jirasakbum** [picotech/picosdk-ni-labview-examples#5]
### Setup

* Example filename:
* Version of LabVIEW 2013 (32/64-bit & Service Pack):
* windows 7
I download PicoScope 6.13.11 (It can open and run)
I download PicoSDK 10.6.12 (64-bit) and install 
copy "picoipp.dll , ps2000.dll , ps2000a.dll" to labview\resource 

I can't open example labview 
 they show can't find Picostatus.vi , PicoErrorHandler.vi is missing etc.

please advise me how to open example picoscope 2206B via labview

**Comment by Jirasakbum** [comment]
Dear Pico
Thank you for your support , Now it’s work on labview


________________________________
40 years Anniversary * 1978 - 2018 * - creating true value
Best Regards
Jirasak Bumrungjit
Test Developer (Software Specialist)

E-mail: Jirasak.Bumrungjit@etk.dk<mailto:Jirasak.Bumrungjit@etk.dk>

ETK EMS Asia Productions Ltd.
No. 64/141 Eastern Seaboard Industrial Estate (Rayong)
Moo 4, Pluakdaeng, Pluakdaeng, Rayong 21140
Thailand

Phone: +66 38 955-839-41
Fax:     +66 38 954-478
Web:    www.etk.dk<http://www.etk.dk/>
________________________________

**Comment by jich77** [comment]
Hello
I have a labview 2017 and I am trying to connect a Pico 5444D and use the Labview examples.
I did not succed to make the examples works.
![capture](https://user-images.githubusercontent.com/30600874/50276695-d803ef80-0442-11e9-9bc2-8410669cf053.PNG)
Thank you in advance

**Comment by ewiebe1** [comment]
As you can see in picosdk-c-sharp-examples-master\ps5000a\PS5000ABlockCapture\PS5000ABlockForm.cs,
the supported models are:
* Supported PicoScope models:
 *
 *		PicoScope 5242A/B & 5442A/B
 *		PicoScope 5243A/B & 5443A/B
 *		PicoScope 5244A/B & 5444A/B

So you need the ps5000a samples. Try it with ps5000a...

@contributors:
Please add a list of all supported models and which samples and dlls must be used.
Add it to the readme.md

**Comment by jich77** [comment]
I will try that

 

Thank you very much 

 

Regards

Javier

**Comment by hsmistry** [comment]
@ewiebe1 & @jich77, please e-mail support@picotech.com for an updated PicoSDK installer, this will resolve the issue with the device not being found. A new SDK is planned for our website.
